format = """
$username\
$time \
$aws\
$winglang\
\n\
$status \
$directory \
$git_branch\
$git_status \
\n \
[ï¬Œ ](#00af00)\
"""

# Disable the blank line at the start of the prompt
#add_newline = true
[cmd_duration]
min_time = 1
format = "[ ğŸ•™ $duration]($style)"

[git_branch]
symbol = "ï˜"
format = "[î‚¶](#ffffff)[ $symbol ](#58C332 bg:#ffffff)[î‚´](#ffffff bg:#58C332)[ $branch ](#ffffff bg:#58C332)"

[git_status]
format = '[$all_status](#ffffff bg:#58C332)[$ahead_behind](#ffffff bg:#58C332)[î‚´](#58C332)'


[time]
disabled = false
format = "[ $time ](#ffffff bg:#609DFB)[î‚´](#609DFB)"
use_12hr = true

[status]
format = "[[î‚¶](#ffffff) $symbol ](#E75053 bg:#ffffff)[î‚´](#ffffff bg:#E75053)[ $status ](#ffffff bg:#E75053)[î‚´](#E75053)"
success_symbol = "ïŸ"
symbol = "ïŸ“"
disabled = false

[golang]
symbol = "î˜¦ "
disabled = false

[winglang]
disabled = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
format = '[î‚¶](#ffffff)[ï© ](#609DFB bg:#ffffff)[î‚´](#ffffff bg:#609DFB)[ $user](#ffffff bg:#609DFB)'

[directory]
format = "[î‚¶](#ffffff)[ ï¼ ](#F7C743 bg:#ffffff)[î‚´](#ffffff bg:#F7C743)[ $path ](#ffffff bg:#F7C743)[î‚´](#F7C743 )"
truncation_length = 5
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "


[aws]
disabled = false
symbol = "ï‰° "
force_display = true
expiration_symbol = "X"
#format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
format = "[î‚¶](#ffffff)[ $symbol ](#ffaf00 bg:#ffffff)[î‚´](#ffffff bg:#ffaf00)[$profile in $region](#ffffff bg:#ffaf00)[î‚´](#ffaf00 bg:#c12626)[expires in: $duration](fg:255 bg:#c12626)[î‚´](#c12626)"
#[aws.region_aliases]
#us-east-1 = "use1"
#us-east-2 = "use2"
#us-west-1 = "usw1"
#us-west-2 = "usw2"
#[aws.profile_aliases]
#sandbox = 'Anything Goes'


